# Generated by Django 5.0.3 on 2024-03-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapimixin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car',
        ),
    ]
