# Generated by Django 5.0.3 on 2024-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapimixin', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'PENDING')]),
        ),
    ]
