# Generated by Django 5.0.3 on 2024-03-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapimixin', '0007_userdto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDto',
        ),
    ]
