# Generated by Django 5.0.3 on 2024-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapimixin', '0008_delete_userdto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
