# Generated by Django 5.0.3 on 2024-03-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapimixin', '0009_userdto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdto',
            options={},
        ),
    ]
